// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wikiSidebar: [
    {
      type: "category",
      label: "🖥️ Computer Science",
      link: {
        type: "doc",
        id: "computer-science",
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "🔻 Algorithm",
          description: "개발자 은퇴 전까지 계속 공부해야 하는 알고리즘",
          link: {
            type: "doc",
            id: "computer-science/algorithm",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "computer-science/algorithm",
            },
          ],
        },
        {
          type: "category",
          label: "📦 Data Structure",
          description: "모든 것의 근본인 자료 구조",
          link: {
            type: "doc",
            id: "computer-science/data-structure",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "computer-science/data-structure",
            },
          ],
        },
        {
          type: "category",
          label: "💾 Database",
          description: "빅데이터도 중요하지만 근본은 스몰데이터",
          link: {
            type: "doc",
            id: "computer-science/database",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "computer-science/database",
            },
          ],
        },
        {
          type: "category",
          label: "🕸️ Distributed System",
          description: "모든 곳에서 쓰이는, 필수 불가결한 분산 시스템",
          link: {
            type: "doc",
            id: "computer-science/distributed-system",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "computer-science/distributed-system",
            },
          ],
        },
        {
          type: "category",
          label: "🌐 Network",
          description: "전세계 사람들과 통신할 수 있도록 만든 네트워크",
          link: {
            type: "doc",
            id: "computer-science/network",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "computer-science/network",
            },
          ],
        },
        {
          type: "category",
          label: "⚙️ Operating System",
          description: "모든 시스템의 근본, 운영체제",
          link: {
            type: "doc",
            id: "computer-science/operating-system",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "computer-science/operating-system",
            },
          ],
        },
      ],
    },
    {
      type: "html",
      value:
        '<hr style="margin: 12px 0; background: var(--ifm-color-emphasis-300);" />',
    },
    {
      type: "category",
      label: "🧭 Paradigm",
      link: {
        type: "doc",
        id: "paradigm",
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "📥 Functional Programming",
          link: {
            type: "doc",
            id: "paradigm/functional-programming",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "paradigm//functional-programming",
            },
          ],
        },
        {
          type: "category",
          label: "🧩 Object-Oriented Programming",
          link: {
            type: "doc",
            id: "paradigm/object-oriented-programming",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "paradigm/object-oriented-programming",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "💬 Language",
      link: {
        type: "doc",
        id: "language",
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "🍋️ Javascript",
          link: {
            type: "doc",
            id: "language/javascript",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "language/javascript",
            },
          ],
        },
        {
          type: "category",
          label: "🐍 Python",
          link: {
            type: "doc",
            id: "language/python",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "language/python",
            },
          ],
        },
        {
          type: "category",
          label: "⚖️ Scala",
          link: {
            type: "doc",
            id: "language/scala",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "language/scala",
            },
          ],
        },
      ],
    },
    {
      type: "html",
      value:
        '<hr style="margin: 12px 0; background: var(--ifm-color-emphasis-300);" />',
    },
    {
      type: "category",
      label: "🎨 Frontend",
      link: {
        type: "doc",
        id: "frontend",
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "💅 CSS",
          link: {
            type: "doc",
            id: "frontend/css",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "frontend/css",
            },
          ],
        },
        {
          type: "category",
          label: "⚛️ React",
          link: {
            type: "doc",
            id: "frontend/react",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "frontend/react",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "☁️ Backend",
      link: {
        type: "doc",
        id: "backend",
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "🌶️ Flask",
          link: {
            type: "doc",
            id: "backend/flask",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "backend/flask",
            },
          ],
        },
        {
          type: "category",
          label: "⚗️ SQLAlchemy",
          link: {
            type: "doc",
            id: "backend/sqlalchemy",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "backend/sqlalchemy",
            },
          ],
        },
      ],
    },
    {
      type: "html",
      value:
        '<hr style="margin: 12px 0; background: var(--ifm-color-emphasis-300);" />',
    },
    {
      type: "category",
      label: "️🔄 DevOps",
      link: {
        type: "doc",
        id: "devops",
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "🐳️ Docker",
          link: {
            type: "doc",
            id: "devops/docker",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "devops/docker",
            },
          ],
        },
        {
          type: "category",
          label: "🐙️ GitHub",
          link: {
            type: "doc",
            id: "devops/github",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "devops/github",
            },
          ],
        },
        {
          type: "category",
          label: "☸️ Kubernetes",
          link: {
            type: "doc",
            id: "devops/kubernetes",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "devops/kubernetes",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "🌊 Data Engineering",
      link: {
        type: "doc",
        id: "data-engineering",
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "🍇 Kafka",
          link: {
            type: "doc",
            id: "data-engineering/kafka",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "data-engineering/kafka",
            },
          ],
        },
        {
          type: "category",
          label: "✨ Spark",
          link: {
            type: "doc",
            id: "data-engineering/spark",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "data-engineering/spark",
            },
          ],
        },
        {
          type: "category",
          label: "🐘 Hadoop",
          link: {
            type: "doc",
            id: "data-engineering/hadoop",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "data-engineering/hadoop",
            },
          ],
        },
        {
          type: "category",
          label: "👀️ Cassandra",
          link: {
            type: "doc",
            id: "data-engineering/cassandra",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "data-engineering/cassandra",
            },
          ],
        },
      ],
    },
    {
      type: "html",
      value:
        '<hr style="margin: 12px 0; background: var(--ifm-color-emphasis-300);" />',
    },
    {
      type: "category",
      label: "🛠️ Tools",
      link: {
        type: "doc",
        id: "tools",
      },
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "tools",
        },
      ],
    },
    {
      type: "category",
      label: "🔍 And More",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "🦖 Docusaurus",
          link: {
            type: "doc",
            id: "etc/docusaurus",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "etc/docusaurus",
            },
          ],
        },
        {
          type: "category",
          label: "💎 Obsidian",
          link: {
            type: "doc",
            id: "etc/obsidian",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "etc/obsidian",
            },
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
