// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [
    "index",
    {
      type: "html",
      value:
        '<hr style="margin: 12px 0; background: var(--ifm-toc-border-color);" />',
    },
    {
      type: "category",
      label: "🖥️ Computer Science",
      link: {
        type: "doc",
        id: "computer-science",
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "🔻 Algorithm",
          description: "개발자 은퇴 전까지 계속 공부해야 하는 알고리즘",
          link: {
            type: "doc",
            id: "computer-science/algorithm",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "computer-science/algorithm",
            },
          ],
        },
        {
          type: "category",
          label: "📦 Data Structure",
          description: "모든 것의 근본인 자료 구조",
          link: {
            type: "doc",
            id: "computer-science/data-structure",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "computer-science/data-structure",
            },
          ],
        },
        {
          type: "category",
          label: "💾 Database",
          description: "빅데이터도 중요하지만 근본은 스몰데이터",
          link: {
            type: "doc",
            id: "computer-science/database",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "computer-science/database",
            },
          ],
        },
        {
          type: "category",
          label: "🕸️ Distributed System",
          description: "모든 곳에서 쓰이는, 필수 불가결한 분산 시스템",
          link: {
            type: "doc",
            id: "computer-science/distributed-system",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "computer-science/distributed-system",
            },
          ],
        },
        {
          type: "category",
          label: "🌐 Network",
          description: "전세계 사람들과 통신할 수 있도록 만든 네트워크",
          link: {
            type: "doc",
            id: "computer-science/network",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "computer-science/network",
            },
          ],
        },
        {
          type: "category",
          label: "⚙️ Operating System",
          description: "모든 시스템의 근본, 운영체제",
          link: {
            type: "doc",
            id: "computer-science/operating-system",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "computer-science/operating-system",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "🌊 Data Engineering",
      link: {
        type: "doc",
        id: "data-engineering",
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "👀️ Cassandra",
          link: {
            type: "doc",
            id: "data-engineering/cassandra",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "data-engineering/cassandra",
            },
          ],
        },
        {
          type: "category",
          label: "🐘 Hadoop",
          link: {
            type: "doc",
            id: "data-engineering/hadoop",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "data-engineering/hadoop",
            },
          ],
        },
        {
          type: "category",
          label: "🍇 Kafka",
          link: {
            type: "doc",
            id: "data-engineering/kafka",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "data-engineering/kafka",
            },
          ],
        },
        {
          type: "category",
          label: "✨ Spark",
          link: {
            type: "doc",
            id: "data-engineering/spark",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "data-engineering/spark",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "👩‍💻 Development",
      link: {
        type: "doc",
        id: "development",
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "🎨 Frontend",
          link: {
            type: "doc",
            id: "development/frontend",
          },
          collapsed: true,
          items: [
            {
              type: "category",
              label: "💅 CSS",
              link: {
                type: "doc",
                id: "development/frontend/css",
              },
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "development/frontend/css",
                },
              ],
            },
            {
              type: "category",
              label: "⚛️ React",
              link: {
                type: "doc",
                id: "development/frontend/react",
              },
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "development/frontend/react",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "☁️ Backend",
          link: {
            type: "doc",
            id: "development/backend",
          },
          collapsed: true,
          items: [
            {
              type: "category",
              label: "🌶️ Flask",
              link: {
                type: "doc",
                id: "development/backend/flask",
              },
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "development/backend/flask",
                },
              ],
            },
            {
              type: "category",
              label: "🍃️Spring",
              link: {
                type: "doc",
                id: "development/backend/spring",
              },
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "development/backend/spring",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "️🔄 Devops",
          link: {
            type: "doc",
            id: "development/devops",
          },
          collapsed: true,
          items: [
            {
              type: "category",
              label: "🐳️ Docker",
              link: {
                type: "doc",
                id: "development/devops/docker",
              },
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "development/devops/docker",
                },
              ],
            },
            {
              type: "category",
              label: "🐙️ GitHub",
              link: {
                type: "doc",
                id: "development/devops/github",
              },
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "development/devops/github",
                },
              ],
            },
            {
              type: "category",
              label: "☸️ Kubernetes",
              link: {
                type: "doc",
                id: "development/devops/kubernetes",
              },
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "development/devops/kubernetes",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "🛠️ Tools",
          link: {
            type: "doc",
            id: "development/tools",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "development/tools",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "💬 Programming Language",
      link: {
        type: "doc",
        id: "programming-language",
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "🍋️ Javascript",
          link: {
            type: "doc",
            id: "programming-language/javascript",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "programming-language/javascript",
            },
          ],
        },
        {
          type: "category",
          label: "🐍 Python",
          link: {
            type: "doc",
            id: "programming-language/python",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "programming-language/python",
            },
          ],
        },
        {
          type: "category",
          label: "🪜 Scala",
          link: {
            type: "doc",
            id: "programming-language/scala",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "programming-language/scala",
            },
          ],
        },
        {
          type: "category",
          label: "📥 Functional Programming",
          link: {
            type: "doc",
            id: "programming-language/functional-programming",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "programming-language/functional-programming",
            },
          ],
        },
      ]
    },
    {
      type: "html",
      value:
          '<hr style="margin: 12px 0; background: var(--ifm-toc-border-color);" />',
    },
    {
      type: "category",
      label: "🎸 ETC.",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "etc",
        },
      ]
    }
  ],
};

module.exports = sidebars;
