// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [
    "index",
    {
      type: "html",
      value: '<hr style="margin: 12px 0;" />',
    },
    {
      type: "category",
      label: "✍️ 공부거리",
      link: {
        type: "doc",
        id: "study-materials",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "study-materials",
        },
      ],
    },
    {
      type: "category",
      label: "🗞️ 읽을거리",
      link: {
        type: "doc",
        id: "articles",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "articles",
        },
      ],
    },
  ],
};

module.exports = sidebars;
