// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [
    "index",
    "bookmark",
    {
      type: "html",
      value: '<hr style="margin: 10px 0;" />',
    },
    {
      type: "category",
      label: "🔻 Algorithm",
      link: {
        type: "generated-index",
        slug: "/algorithm",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "algorithm",
        },
      ],
    },
    {
      type: "category",
      label: "💅 CSS",
      link: {
        type: "generated-index",
        slug: "/css",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "css",
        },
      ],
    },
    {
      type: "category",
      label: "🛠️ Devtool",
      link: {
        type: "generated-index",
        slug: "/devtool",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "devtool",
        },
      ],
    },
    {
      type: "category",
      label: "🐋 Docker",
      link: {
        type: "generated-index",
        slug: "/docker",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "docker",
        },
      ],
    },
    {
      type: "category",
      label: "🦖 Docusaurus",
      link: {
        type: "generated-index",
        slug: "/docusaurus",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "docusaurus",
        },
      ],
    },
    {
      type: "category",
      label: "🌶️ Flask",
      link: {
        type: "generated-index",
        slug: "/flask",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "flask",
        },
      ],
    },
    {
      type: "category",
      label: "🐍 Python",
      link: {
        type: "generated-index",
        slug: "/python",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "python",
        },
      ],
    },
    {
      type: "category",
      label: "🍯 Tips",
      link: {
        type: "generated-index",
        slug: "/tips",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "tips",
        },
      ],
    },
  ],
};

module.exports = sidebars;
