// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [
    "index",
    {
      type: "html",
      value:
        '<hr style="margin: 12px 0; background: var(--ifm-toc-border-color);" />',
    },
    {
      type: "category",
      label: "🖥️ Computer Science",
      link: {
        type: "doc",
        id: "computer-science",
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "🔻 Algorithm",
          description: "개발자 은퇴 전까지 계속 공부해야 하는 알고리즘",
          link: {
            type: "doc",
            id: "computer-science/algorithm",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "computer-science/algorithm",
            },
          ],
        },
        {
          type: "category",
          label: "📦 Data Structure",
          description: "모든 것의 근본인 자료 구조",
          link: {
            type: "doc",
            id: "computer-science/data-structure",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "computer-science/data-structure",
            },
          ],
        },
        {
          type: "category",
          label: "💾 Database",
          description: "빅데이터도 중요하지만 근본은 스몰데이터",
          link: {
            type: "doc",
            id: "computer-science/database",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "computer-science/database",
            },
          ],
        },
        {
          type: "category",
          label: "🕸️ Distributed System",
          description: "모든 곳에서 쓰이는, 필수 불가결한 분산 시스템",
          link: {
            type: "doc",
            id: "computer-science/distributed-system",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "computer-science/distributed-system",
            },
          ],
        },
        {
          type: "category",
          label: "🌐 Network",
          description: "전세계 사람들과 통신할 수 있도록 만든 네트워크",
          link: {
            type: "doc",
            id: "computer-science/network",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "computer-science/network",
            },
          ],
        },
        {
          type: "category",
          label: "⚙️ Operating System",
          description: "모든 시스템의 근본, 운영체제",
          link: {
            type: "doc",
            id: "computer-science/operating-system",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "computer-science/operating-system",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "🌨️ Data Engineering",
      link: {
        type: "doc",
        id: "data-engineering",
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "👁️ Cassandra",
          link: {
            type: "doc",
            id: "data-engineering/cassandra",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "data-engineering/cassandra",
            },
          ],
        },
        {
          type: "category",
          label: "🐘 Hadoop",
          link: {
            type: "doc",
            id: "data-engineering/hadoop",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "data-engineering/hadoop",
            },
          ],
        },
        {
          type: "category",
          label: "🍇 Kafka",
          link: {
            type: "doc",
            id: "data-engineering/kafka",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "data-engineering/kafka",
            },
          ],
        },
        {
          type: "category",
          label: "✨ Spark",
          link: {
            type: "doc",
            id: "data-engineering/spark",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "data-engineering/spark",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "👩‍💻 Software Engineering",
      link: {
        type: "doc",
        id: "software-engineering",
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "💅 CSS",
          link: {
            type: "generated-index",
            slug: "/css",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "software-engineering/css",
            },
          ],
        },
        {
          type: "category",
          label: "🐋 Docker",
          link: {
            type: "doc",
            id: "software-engineering/docker",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "software-engineering/docker",
            },
          ],
        },
        {
          type: "category",
          label: "🌶️ Flask",
          link: {
            type: "doc",
            id: "software-engineering/flask",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "software-engineering/flask",
            },
          ],
        },
        {
          type: "category",
          label: "📥 Functional Programming",
          link: {
            type: "doc",
            id: "software-engineering/functional-programming",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "software-engineering/functional-programming",
            },
          ],
        },
        {
          type: "category",
          label: "🐙 GitHub",
          link: {
            type: "doc",
            id: "software-engineering/github",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "software-engineering/github",
            },
          ],
        },
        {
          type: "category",
          label: "🐍 Python",
          link: {
            type: "doc",
            id: "software-engineering/python",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "software-engineering/python",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "🎸 ETC.",
      link: {
        type: "generated-index",
        slug: "/etc",
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "🛠️ Devtool",
          link: {
            type: "generated-index",
            slug: "/devtool",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "etc/devtool",
            },
          ],
        },
        "etc/docusaurus",
        {
          type: "category",
          label: "🪨 Obsidian",
          link: {
            type: "doc",
            id: "etc/obsidian",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "etc/obsidian",
            },
          ],
        },
        {
          type: "category",
          label: "🍯 Tips",
          link: {
            type: "generated-index",
            slug: "/tips",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "etc/tips",
            },
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
