// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [
    "index",
    {
      type: "html",
      value: '<hr style="margin: 10px 0;" />',
    },
    {
      type: "category",
      label: "Apache / Airflow",
      link: {
        type: "generated-index",
        slug: "/apache-airflow",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "apache-airflow",
        },
      ],
    },
  ],
};

module.exports = sidebars;
